"""
Schema definitions for generated security alerts.

This module defines the data contract used when BlackTrace creates and
returns alerts from detected security threats.
"""
from pydantic import BaseModel
from datetime import datetime

class SecurityAlert(BaseModel):
    """
    Response model for a security alert generated by BlackTrace.

    Alerts represent detection outcomes that require tracking, review,
    or incident response action.
    """
    alert_id: int
    threat_type: str
    source_ip: str
    severity: str
    status: str
    timestamp: datetime
    recommended_action: str
