import asyncio
from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy.orm import Session
from app.database.session import get_db

from typing import Dict, Union

from detection_engine.inference import predict_telemetry
from intelligence.workflow import intelligence_workflow
from app.services.intelligence_service import save_intelligence_report
from app.services.alert_manager import create_alert
from app.services.websocket_manager import manager

router = APIRouter()

class TelemetryRequest(BaseModel):
    telemetry: Dict[str, Union[str, float, int]]

@router.post("/analyze")
async def analyze_telemetry(request: TelemetryRequest, db: Session = Depends(get_db)):
    """
    Analyze incoming telemetry using BlackTrace ML inference pipeline.
    """

    predict_result = predict_telemetry(request.telemetry)
    threat_analysis = {
        "threat_type": predict_result["attack_type"],
        "source_ip": predict_result["source_ip"],
        "recommended_action": "Generated by intelligence workflow"
    }

    alert = create_alert(threat_analysis=threat_analysis, db=db)

    intelligence_result = intelligence_workflow.invoke(
        {
            "alert": predict_result
        }
    )

    asyncio.create_task(
        manager.broadcast(
            {
                "event": "incident_analysis",
                "alert_id": alert.alert_id,
                "data": intelligence_result["incident_report"]
            }
        )
    )

    asyncio.create_task(
        manager.broadcast(
            {
                "event": "recommendations",
                "alert_id": alert.alert_id,
                "data": intelligence_result["recommendations"]
            }
        )
    )

    save_intelligence_report(
        db=db,
        alert_id=alert.alert_id,
        incident_analysis=intelligence_result["incident_report"],
        recommendations=intelligence_result["recommendations"]
    )

    return {
        "status": "success",
        "detection": predict_result,
        "incident_analysis": intelligence_result["incident_report"],
        "recommendations": intelligence_result["recommendations"]
    }
