import asyncio
from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy.orm import Session
from app.database.session import get_db

from typing import Dict, Union

from detection_engine.inference import predict_telemetry
from intelligence.workflow import intelligence_workflow
from app.schemas.network_flow_schema import NetworkFlow
from app.services.detection_service import detection_service
from app.services.intelligence_service import save_intelligence_report
from app.services.alert_manager import create_alert
from app.services.websocket_manager import manager
from app.security.auth import verify_api_key

router = APIRouter()

@router.post("/analyze")
async def analyze_telemetry(flow: NetworkFlow, db: Session = Depends(get_db), api_key: str = Depends(verify_api_key)):
    """
    Analyze incoming telemetry using BlackTrace ML inference pipeline.
    """

    predict_result = detection_service.predict(flow)
    threat_analysis = {
        "threat_type": predict_result["attack_type"],
        "source_ip": flow.source_ip,
        "recommended_action": "Generated by intelligence workflow"
    }

    alert = create_alert(threat_analysis=threat_analysis, db=db)

    alert_info = {
        "attack_type": predict_result["attack_type"],
        "confidence": predict_result["confidence"],
        "is_anomaly": predict_result["is_anomaly"],
        "anomaly_score": predict_result["anomaly_score"],
        "source_ip": flow.source_ip,
        "timestamp": flow.timestamp.isoformat()
    }
    intelligence_result = intelligence_workflow.invoke(
        {
            "alert": alert_info
        }
    )

    asyncio.create_task(
        manager.broadcast(
            {
                "event": "incident_analysis",
                "alert_id": alert.alert_id,
                "data": intelligence_result["incident_report"]
            }
        )
    )

    asyncio.create_task(
        manager.broadcast(
            {
                "event": "recommendations",
                "alert_id": alert.alert_id,
                "data": intelligence_result["recommendations"]
            }
        )
    )

    save_intelligence_report(
        db=db,
        alert_id=alert.alert_id,
        incident_analysis=intelligence_result["incident_report"],
        recommendations=intelligence_result["recommendations"]
    )

    return {
        "status": "success",
        "detection": predict_result,
        "incident_analysis": intelligence_result["incident_report"],
        "recommendations": intelligence_result["recommendations"]
    }
